name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Debug with Gradle
      run: cd android && ./gradlew tasks --all
    - name: Build with Gradle
      run: ./gradlew build assembleDebug
    - name: Upload artifact
      uses: ShaunLWM/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: android/app/build/outputs/apk/debug
       RELEASE_TITLE: ESWifi Android Build
