name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./android/gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ESWifi-android
        path: app
