name: APK static analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install npm dependencies
      run: npm install
    - name: Previous build with npm
      run: npm run build:sync
    - name: Basic dependencies check
      working-directory: ./android
      run: ./gradlew lint
